#ifndef HAL_CONFIG_H
#define HAL_CONFIG_H

#include "em_device.h"
#include "hal-config-types.h"

// This file is auto-generated by Hardware Configurator in Simplicity Studio.
// Any content between $[ and ]$ will be replaced whenever the file is regenerated.
// Content outside these regions will be preserved.

// $[ACMP0]
// [ACMP0]$

// $[ACMP1]
// [ACMP1]$

// $[ADC0]
#define PORTIO_ADC0_POS_PIN              (10)
#define PORTIO_ADC0_POS_PORT             (gpioPortD)
#define PORTIO_ADC0_POS_LOC              (_ADC_SINGLECTRL_POSSEL_APORT3XCH2)

// [ADC0]$

// $[BTL_BUTTON]
// [BTL_BUTTON]$

// $[BUTTON]
// [BUTTON]$

// $[CMU]
// [CMU]$

// $[CSEN0]
// [CSEN0]$

// $[DCDC]
// [DCDC]$

// $[EMU]
// [EMU]$

// $[EXTFLASH]
// [EXTFLASH]$

// $[GPIO]
// [GPIO]$

// $[I2C0]
// [I2C0]$

// $[I2C1]
// [I2C1]$

// $[I2CSENSOR]
// [I2CSENSOR]$

// $[IDAC0]
// [IDAC0]$

// $[IOEXP]
// [IOEXP]$

// $[LED]
// [LED]$

// $[LESENSE]
#define PORTIO_LESENSE_CH0_PIN           (8)
#define PORTIO_LESENSE_CH0_PORT          (gpioPortD)
#define PORTIO_LESENSE_ROUTE_LOC         (0)

// [LESENSE]$

// $[LETIMER0]
// [LETIMER0]$

// $[LEUART0]
// [LEUART0]$

// $[LFXO]
// [LFXO]$

// $[PCNT0]
// [PCNT0]$

// $[PCNT1]
// [PCNT1]$

// $[PCNT2]
// [PCNT2]$

// $[PORTIO]
// [PORTIO]$

// $[PRS]
// [PRS]$

// $[PTI]
// [PTI]$

// $[SERIAL]
// [SERIAL]$

// $[SPIDISPLAY]
// [SPIDISPLAY]$

// $[SPINCP]
// [SPINCP]$

// $[TIMER0]
// [TIMER0]$

// $[TIMER1]
// [TIMER1]$

// $[UARTNCP]
// [UARTNCP]$

// $[USART0]
#define PORTIO_USART0_RX_PIN             (8)
#define PORTIO_USART0_RX_PORT            (gpioPortC)
#define PORTIO_USART0_RX_LOC             (12)

#define PORTIO_USART0_TX_PIN             (7)
#define PORTIO_USART0_TX_PORT            (gpioPortC)
#define PORTIO_USART0_TX_LOC             (12)

#define HAL_USART0_ENABLE                (1)

#define BSP_USART0_RX_PIN                (8)
#define BSP_USART0_RX_PORT               (gpioPortC)
#define BSP_USART0_RX_LOC                (12)
#define UART_RX_PIN                      (8)
#define UART_RX_PORT                     (gpioPortC)
#define UART_RX_LOC                      (12)

#define BSP_USART0_TX_PIN                (7)
#define BSP_USART0_TX_PORT               (gpioPortC)
#define BSP_USART0_TX_LOC                (12)
#define UART_TX_PIN                      (7)
#define UART_TX_PORT                     (gpioPortC)
#define UART_TX_LOC                      (12)

#define HAL_USART0_BAUD_RATE             (115200)
#define HAL_USART0_FLOW_CONTROL          (HAL_USART_FLOW_CONTROL_NONE)
#define UART_BAUD_RATE                   (115200)
#define UART_FLOW_CONTROL                (HAL_USART_FLOW_CONTROL_NONE)
// [USART0]$

// $[USART1]
#define PORTIO_USART1_CLK_PIN            (2)
#define PORTIO_USART1_CLK_PORT           (gpioPortA)
#define PORTIO_USART1_CLK_LOC            (0)

#define PORTIO_USART1_CS_PIN             (3)
#define PORTIO_USART1_CS_PORT            (gpioPortA)
#define PORTIO_USART1_CS_LOC             (0)

#define PORTIO_USART1_RX_PIN             (1)
#define PORTIO_USART1_RX_PORT            (gpioPortA)
#define PORTIO_USART1_RX_LOC             (0)

#define PORTIO_USART1_TX_PIN             (0)
#define PORTIO_USART1_TX_PORT            (gpioPortA)
#define PORTIO_USART1_TX_LOC             (0)

#define HAL_USART1_ENABLE                (1)

#define BSP_USART1_CS_PIN                (3)
#define BSP_USART1_CS_PORT               (gpioPortA)
#define BSP_USART1_CS_LOC                (0)
#define SPI_CS_PIN                       (3)
#define SPI_CS_PORT                      (gpioPortA)
#define SPI_CS_LOC                       (0)

#define BSP_USART1_CLK_PIN               (2)
#define BSP_USART1_CLK_PORT              (gpioPortA)
#define BSP_USART1_CLK_LOC               (0)
#define SPI_CLK_PIN                      (2)
#define SPI_CLK_PORT                     (gpioPortA)
#define SPI_CLK_LOC                      (0)

#define BSP_USART1_MISO_PIN              (1)
#define BSP_USART1_MISO_PORT             (gpioPortA)
#define BSP_USART1_MISO_LOC              (0)
#define SPI_MISO_PIN                     (1)
#define SPI_MISO_PORT                    (gpioPortA)
#define SPI_MISO_LOC                     (0)

#define BSP_USART1_MOSI_PIN              (0)
#define BSP_USART1_MOSI_PORT             (gpioPortA)
#define BSP_USART1_MOSI_LOC              (0)
#define SPI_MOSI_PIN                     (0)
#define SPI_MOSI_PORT                    (gpioPortA)
#define SPI_MOSI_LOC                     (0)

#define HAL_USART1_FREQUENCY             (1000000)
#define SPI_FREQUENCY                    (1000000)
// [USART1]$

// $[USART2]
// [USART2]$

// $[USART3]
// [USART3]$

// $[VCOM]
// [VCOM]$

// $[VDAC0]
// [VDAC0]$

// $[WDOG]
// [WDOG]$

// $[WTIMER0]
// [WTIMER0]$

// $[WTIMER1]
// [WTIMER1]$

#endif /* HAL_CONFIG_H */

// $[Custom pin names]
#define LED_PIN                          (14)
#define LED_PORT                         (gpioPortD)

// [Custom pin names]$

